version: '3.8'

services:
  backend:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8081
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  simulator:
    build: .
    command: python simulator/simulator.py
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./data:/app/data
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
